apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-staging
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - values-staging.yaml
    path: project/helm 
    repoURL: https://github.com/abdul-gulfarosh/tech-trends
    targetRevision: HEAD
  # Sync policy
  syncPolicy: {}